### ISSUE TITLE
Continuation

### ISSUE THREAD

**Issue by LostSoulfly** [darcymiranda/PFire#1]
I see this hasn't been touched in a few years -- do you have any plans to continue development?

Personally, I know very little C# but an xfire server emulator has been a project in the back of my mind since the servers shutdown. I have many fond memories of Xfire (I met my wife through Xfire, ironically) and would love to see it more functional. I hex edited the Xfire client to point to my server and it works well for connecting.

Few things I've noticed:
When connecting and creating a new user it seems to disconnect existing connections.
Voice chat doesn't work? Not sure if the server is involved as it used to be p2p, but the server may initiate it somehow.
Chatrooms don't seem to do anything.
Disconnected users don't ever show as offline.
The sqlite gave me trouble, I had to copy the DLL into the output folders in order to get it to run. (I've no experience with sqlite, either)

It's exciting to see even this much work already put into it! Thanks!

**Comment by darcymiranda** [comment]
Glad to hear you're interested in the project. I lost a lot of motivation to continue working on this after getting some of the more simpler features working.

P2P, chat rooms and pretty much 95% of all the features XFire provided at the time is not implemented, but the groundwork of the protocol has been mostly laid out.

I do somewhat remember witnessing some of the bugs that you experienced with user statuses and disconnections.

The documentation on the protocol is a tad rudimentary and has only ever been done from the client's perspective. I saved a copy [here](https://dl.dropboxusercontent.com/u/12374095/XFire%20Protocol/index.xhtml), if you're interested. I'm still very much thankful to the author as it definitely saved me a ton of time.

Seeing as other people are interested, I'll see if I can get my motivation reignited again 👍

**Comment by LostSoulfly** [comment]
Good to hear! A few years ago I gave a quick look at the protocols and found a bit of documentation myself that I tucked away in a dropbox folder and forgot about. It's not a lot, and I'm sure the link you provided has quite a bit of information that my small archive doesn't have, but it may prove useful as well.

Should that motivation happen to be reignited, I'll certainly be following the progress and hopefully be able to assist. I've been wanting to get more acquainted with c# and this looks like (albeit a more advanced than is recommended) a nice starting point.

[xfire.zip](https://github.com/darcymiranda/PFire/files/769050/xfire.zip)

**Comment by darcymiranda** [comment]
Thanks for the extra documentation; anything helps.

Feel free to tinker around, and if you think you made any progress, definitely open up a pull request.

**Comment by Alauraa** [comment]
This hasn't been touched in 2 years, but i'd recommend a discord for this, so people can maybe start again and fixing this up, i would love to have a Xfire revival project. It'd be great to use this again as Xfire is what got me into gaming. If you ever want a discord server, give me a shout!

**Comment by darcymiranda** [comment]
Glad to hear you're interested, Alauraa! 

I'll need to refactor large swaths of the repository before I'd feel comfortable with people contributing as the code is quite old and not the greatest. This weekend, or next, I will fix up the readme to explain how to get the correct version of XFire connecting to the PFire server.

At some point, I will also need to remember what's been done and what is left doing so that ya'll can submit PRs on particular features.

I like the discord idea, feel free to set it up and throw the link somewhere 😃

**Comment by LostSoulfly** [comment]
I'm still watching the repo too :)

**Comment by Alauraa** [comment]
> Glad to hear you're interested, Alauraa!
> 
> I'll need to refactor large swaths of the repository before I'd feel comfortable with people contributing as the code is quite old and not the greatest. This weekend, or next, I will fix up the readme to explain how to get the correct version of XFire connecting to the PFire server.
> 
> At some point, I will also need to remember what's been done and what is left doing so that ya'll can submit PRs on particular features.
> 
> I like the discord idea, feel free to set it up and throw the link somewhere 😃

https://discord.gg/J4eqUFK

Feel free to invite anyone and everyone using that link, as well as i did get it up and running, i just never got around to finding the hex code for Xfire to change it to use Pfire as a login server and or etc.

**Comment by darcymiranda** [comment]
> I'm still watching the repo too :)

Glad you're still interested as well! 👋 

> i just never got around to finding the hex code for Xfire to change it to use Pfire as a login server and or etc.

For development, I just used my windows host file to route the IP XFire is connecting with to my own. I can't remember what the IP is, but you can use Wireshark to find out. I'll make sure I get all that info in the readme this month.

**Comment by LostSoulfly** [comment]
It's been a while but I seem to recall hex editing the executable itself.
When I get home from work today I'll see if I can dig up my patched client
and any notes I stuffed away.

edit: I found it on my server. It looks like I simply opened up the EXE and replaced all the URLs/IPs with 127.0.0.1. Here's my folder from way back. I'd recommend you compare it to the official EXE to make sure there's nothing malicious in it and not trust the word of some random stranger.
[Xfire.zip](https://github.com/darcymiranda/PFire/files/3584808/Xfire.zip)

**Comment by Alauraa** [comment]
I also have the documentation from ealryier in this conversation. I can host that on my web server if need be. As well as there is a wiki software that allows editing from github to the remote server. WikiJS

**Comment by Alauraa** [comment]
So, as a note, if you hex-edit the EXE, you can put in cs.xfire.com and put in a random string that is 12 characters or shorter, we already have a idea of how to do it in the future if what we plan works. But temporarily. cs.xfire.com can be anything 12 characters or short, I use HxD to modify the exe.

**Comment by LostSoulfly** [comment]
The zip file I attached contains an already hex-edited xfire.exe to redirect to 127.0.0.1 :-)

**Comment by Alauraa** [comment]
Yes, but we are trying to get it on a server to work with eventually cs.xfire.com if it expires and we can grab it.  By the way SoulFly, if you wouldn't mind joining the discord. it'd help in conversation.

**Comment by LostSoulfly** [comment]
To be fair, you didn't mention anything about that trying to obtain the original domain. And in the case that you do, you won't need to hex-edit anything so I'm not sure I understand where you were going with this in the first place...?

And sorry, I only really have free time at the while I'm at work where I do not have access to Discord.

**Comment by Alauraa** [comment]
> To be fair, you didn't mention anything about that trying to obtain the original domain. And in the case that you do, you won't need to hex-edit anything so I'm not sure I understand where you were going with this in the first place...?

For right now, we can't exactly use cs.xfire.com as we don't have it, also when you get home you can join, no rush yknow.

**Comment by darcymiranda** [comment]
Closing as conversation moved to discord
