### ISSUE TITLE
Clients report "High latency detected between you are the server" when runing on local wifi

### ISSUE THREAD

**Issue by TheLogster** [darcymiranda/PFire#19]
Even though ping is allowed and the client reports ttl as being ~5ms

Can we verify under what conditions this message appears, as I don't belive that it has anything to do with the actual networking?

Does the keep alive message need to be implemented?

**Comment by darcymiranda** [comment]
Related disussions [here](https://github.com/darcymiranda/PFire/issues/25)

**Comment by darcymiranda** [comment]
This is not a network issue with the server but rather how the client implements P2P.
