### ISSUE TITLE
I found the source code for XFire

### ISSUE THREAD

**Issue by celluj34** [darcymiranda/PFire#23]
Long story short, their SVN is still active on sphene.net, and (after a few redirects) I was able to locate the URL for their repo: http://source.sphene.net/svn/xfirelib/trunk/xfirelib

So I've cloned it into git (using `git svn clone`) and have made it available on github: https://github.com/celluj34/xfire

So now we should be able to figure out what the other messages are for, if someone is skilled in C++.

Edit: And it looks like there are some other repos available if you go up one level: http://source.sphene.net/svn/xfirelib/trunk/

**Comment by celluj34** [comment]
There's a `protocol.odt` file in there that I'm working on converting to markdown, it's got some interesting bits in there: https://github.com/celluj34/xfire/blob/master/gfire/protocol.odt

**Comment by darcymiranda** [comment]
Nice find I remember looking at a c++ xfire client project to help build some of the more complex server interactions. It's very helpful.

IIRC these are third party clients and not directly affiliated. I could be wrong though I didn't dig too deep in your link.

Here's another client project on GitHub https://github.com/jasarien/Xblaze-iOS

I don't think I read through the odt file

**Comment by darcymiranda** [comment]
Here's another one on GitHub https://github.com/jasarien/Xblaze-iOS with objective c.

There's a Java one too somewhere on the internet if I remember correctly.

**Comment by celluj34** [comment]
All done! https://github.com/celluj34/xfire/blob/master/gfire/protocol.md

I don't think it needs to be in your repo, per se, but you can always grab a copy of it if you like.
