### ISSUE TITLE
TcpServer.Listen wrapping Accept in Task.Run is a bug. Additionally, half of the project using async/await and half not can lead to unexpected threading problems, like race conditions. Unless otherwise required the project should be "async all the way."

### ISSUE THREAD

**Issue by AjdinoX** [darcymiranda/PFire#26]

**Comment by TheLogster** [comment]
I don't believe this to be a bug, the async task allows the server to continually accept connections, which then fires up a client to handle this new connection in its own thread. The reads from the client don't need to be async, as they are in their own thread.

**Comment by darcymiranda** [comment]
Agreed. Since @celluj34 installed dotnet's DI container, it's async all the way through now. I updated the listen method to be async so we don't need to do `Task.Run()` now. Commit [here](https://github.com/darcymiranda/PFire/commit/675120ebefcd12ff7a79fa771b9d4b3cbaba3bac)
