### ISSUE TITLE
There are no Endianess checks. This can matter if users have different operating systems or implementations.

### ISSUE THREAD

**Issue by AjdinoX** [darcymiranda/PFire#27]

**Comment by TheLogster** [comment]
Any information in endianess in dotner core tcpclient?

I have examined the msdn and seen example projects for both windows and linux, all with no mention of endianess

**Comment by darcymiranda** [comment]
I may be ignorant to the problem, but I don't think this is an issue. The XFire client can only run on Windows. I'd strike this as an issue not worth investigating until it becomes an actual problem.

I'll close in a couple days if I don't hear see a counter argument otherwise.

**Comment by TheLogster** [comment]
The client that is used, is windows only, and I can't find any dotnet core examples for servers using tcplistener/tcpclient that mention endianess..

I think this is a non-issue.
