### ISSUE TITLE
Introduce message bus-style communication

### ISSUE THREAD

**Issue by celluj34** [darcymiranda/PFire#29]
Right now we "manually" keep a track of all the sessions (with users) that we are connected to.

I propose we envision the internals as a pub-sub model; when a new client connects and logs in, they subscribe to all of the messages in such a way that when messages are published (either for _all_ consumers or _specific_ consumers), the subscribers themselves can send messages to their own `TcpClient`. When one disconnects, they remove their subscriptions and dispose their connection, etc.

I have worked with solutions like SignalR, but I think it's overkill and recommend we find a way to host it in-memory (or even as a separate `HostedService`).

**Comment by darcymiranda** [comment]
I agree that following the message flow can be very confusing if you don't already know how it works. For example, all the various messages that are exchanged for a successful login. 

I'm going to try to implement a solution for this over the next week or so. I have had some ideas in my head for a long time that I just never got around to implementing.

**Comment by celluj34** [comment]
I have been told ZeroMQ may be a good choice for an in-process message queuing system: https://zeromq.org/
