### ISSUE TITLE
cant verify in the the discord server

### ISSUE THREAD

**Issue by zzx-the-neptune** [darcymiranda/PFire#36]
![image](https://user-images.githubusercontent.com/67794972/117532702-7d5a9680-aff1-11eb-9252-41927a735714.png)
![image](https://user-images.githubusercontent.com/67794972/117532712-8a778580-aff1-11eb-8376-8e1188aa7e42.png)

**Comment by zzx-the-neptune** [comment]
now where?

**Comment by zzx-the-neptune** [comment]
nvm

**Comment by omegabr99** [comment]
how did u verify?
