### ISSUE TITLE
Ubuntu.

### ISSUE THREAD

**Issue by tudat-lan** [darcymiranda/PFire#37]
Hy How to set the server to run automatically? Or delete usernames?

**Comment by tudat-lan** [comment]
xfirepfire.service 

`[Unit]
Description=Xfire szerver

[Service]
Type=simple
User=root
ExecStart=/opt/xfirestart.sh

[Install]
WantedBy=multi-user.target`

xfirestart.sh

`#!/bin/sh
cd /opt/PFire/src/PFire.Console/
dotnet run`

cd /opt/
sh xfirestart.sh

Couldn't find a project to run. Ensure a project exists in /opt, or pass the path to the project using --project.

**Comment by darcymiranda** [comment]
Did you build/publish the binaries? `dotnet publish`. I never got around to publishing releases for folks to just download the binaries. 

Here's how I setup the service for the community server:
```
[Unit]
Wants=network.target
After=syslog.target network-online.target

[Service]
Type=simple
WorkingDirectory=/home/ubuntu/PFire/out
ExecStart=/home/ubuntu/dotnet/dotnet PFire.Console.dll
Restart=on-failure
RestartSec=5
KillMode=process

[Install]
WantedBy=multi-user.target
```

Hope that helps. Sorry about the late response.
