### ISSUE TITLE
Can't send messages after a few hours of the server running [high latency issue] (rebooting server fixes this but only temporally)

### ISSUE THREAD

**Issue by AjdinoX** [darcymiranda/PFire#6]

**Comment by TheLogster** [comment]
The PR has been merged... that should improve things.

**Comment by darcymiranda** [comment]
@TheLogster did we ever test to see if your net changes fixed this issue? @AjdinoX

**Comment by AjdinoX** [comment]
> @TheLogster did we ever test to see if your net changes fixed this issue? @AjdinoX

No one's asked me to do a test, but I've been looking forward to being asked.

**Comment by darcymiranda** [comment]
This is not a network issue with the server but rather how the client implements P2P.
